import React, { useEffect, useState } from 'react';
import api from '@/lib/api';
import { motion } from 'framer-motion';
import { AlertCircle, TrendingUp, Anchor, Activity, Zap, ShieldCheck, AlertTriangle, Layers, DollarSign } from 'lucide-react';
import { Card, CardContent } from "@/components/ui/card";

const ExecutiveBrief = () => {
    const [brief, setBrief] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchBrief = async () => {
            try {
                const res = await api.get('/api/brief');
                setBrief(res.data);
            } catch (error) {
                console.error("Failed to fetch executive brief", error);
            } finally {
                setLoading(false);
            }
        };
        fetchBrief();
    }, []);

    if (loading) return (
        <div className="w-full h-96 bg-slate-50/50 rounded-xl animate-pulse mb-8 border border-slate-200" />
    );

    if (!brief) return null;

    // Helper to bold markdown-like text
    const formatText = (text) => {
        const parts = text.split(/(\*\*.*?\*\*)/g);
        return parts.map((part, index) => {
            if (part.startsWith('**') && part.endsWith('**')) {
                return <span key={index} className="font-bold text-slate-900">{part.slice(2, -2)}</span>;
            }
            return part;
        });
    };

    return (
        <section className="mb-8 font-sans">
            {/* Header */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-8"
            >
                <div className="flex items-center space-x-2 mb-2">
                    <div className="px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-xs font-bold uppercase tracking-wider flex items-center">
                        <Zap size={12} className="mr-1" />
                        AI Decision Engine
                    </div>
                </div>
                <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Weekly AI Decision Brief — Week 24</h1>
                <p className="text-slate-500 text-lg">Factory and inventory actions generated by LensOS AI</p>
            </motion.div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* PRIMARY DIRECTIVE */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: 0.1 }}
                    className="lg:col-span-2"
                >
                    <Card className="h-full bg-gradient-to-br from-[#00BAC6] to-[#008f99] text-white border-none shadow-xl overflow-hidden relative">
                        {/* Background Decoration */}
                        <div className="absolute top-0 right-0 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl -mr-32 -mt-32 pointer-events-none" />
                        <div className="absolute bottom-0 left-0 w-48 h-48 bg-black opacity-10 rounded-full blur-3xl -ml-24 -mb-24 pointer-events-none" />

                        <CardContent className="p-8 relative z-10 flex flex-col justify-center h-full">
                            <div className="flex items-center space-x-2 mb-6">
                                <Activity className="text-white/80" />
                                <span className="text-sm font-bold uppercase tracking-widest text-white/80">Primary Directive</span>
                            </div>
                            <p className="text-2xl leading-relaxed font-medium text-white/95">
                                {formatText(brief.directive)}
                            </p>
                        </CardContent>
                    </Card>
                </motion.div>

                {/* KEY ACTIONS LIST */}
                <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.2 }}
                    className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 flex flex-col"
                >
                    <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center">
                        <ShieldCheck className="mr-2 text-emerald-600" size={20} />
                        Immediate Actions
                    </h3>
                    <ul className="space-y-4 flex-1">
                        {brief.actions.map((action, i) => (
                            <li key={i} className="flex items-start">
                                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-slate-100 text-slate-600 flex items-center justify-center text-xs font-bold mr-3 mt-0.5">
                                    {i + 1}
                                </span>
                                <span className="text-slate-600 text-sm leading-relaxed">
                                    {formatText(action)}
                                </span>
                            </li>
                        ))}
                    </ul>

                    {/* Capacity Narrative Block */}
                    <div className="mt-6 p-4 bg-slate-50 rounded-lg border border-slate-100">
                        <div className="flex items-center text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                            <Anchor size={12} className="mr-1" />
                            Capacity Note
                        </div>
                        <p className="text-sm text-slate-600">
                            {formatText(brief.capacity_narrative)}
                        </p>
                    </div>

                    {/* Confidence Narrative Block */}
                    {brief.confidence_narrative && (
                        <div className="mt-4 p-4 bg-indigo-50 rounded-lg border border-indigo-100">
                            <div className="flex items-center text-xs font-bold text-indigo-400 uppercase tracking-wider mb-2">
                                <Zap size={12} className="mr-1" />
                                AI Confidence
                            </div>
                            <p className="text-sm text-slate-600">
                                {formatText(brief.confidence_narrative)}
                            </p>
                        </div>
                    )}
                </motion.div>
            </div>

            {/* FINANCIAL IMPACT & RISK */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6 mt-8">
                {/* Financial Cards */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.3 }}
                    className="bg-white p-5 rounded-xl border border-emerald-100 shadow-sm hover:shadow-md transition-all"
                >
                    <div className="text-xs font-bold text-emerald-600 uppercase tracking-wider mb-1">Revenue Protected</div>
                    <div className="text-2xl font-extrabold text-slate-900">₹{(brief.financials.revenue_protected / 1e6).toFixed(1)}M</div>
                    <div className="text-xs text-slate-400 mt-1 flex items-center">
                        <TrendingUp size={12} className="mr-1 text-emerald-500" />
                        From optimized plan
                    </div>
                </motion.div>

                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.4 }}
                    className="bg-white p-5 rounded-xl border border-rose-100 shadow-sm hover:shadow-md transition-all"
                >
                    <div className="text-xs font-bold text-rose-600 uppercase tracking-wider mb-1">Revenue At Risk</div>
                    <div className="text-2xl font-extrabold text-slate-900">₹{(brief.financials.revenue_risk / 1e6).toFixed(1)}M</div>
                    <div className="text-xs text-slate-400 mt-1 flex items-center">
                        <AlertTriangle size={12} className="mr-1 text-rose-500" />
                        If allocations fail
                    </div>
                </motion.div>

                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.5 }}
                    className="bg-white p-5 rounded-xl border border-blue-100 shadow-sm hover:shadow-md transition-all"
                >
                    <div className="text-xs font-bold text-blue-600 uppercase tracking-wider mb-1">Working Capital</div>
                    <div className="text-2xl font-extrabold text-slate-900">₹{(brief.financials.working_capital / 1e6).toFixed(1)}M</div>
                    <div className="text-xs text-slate-400 mt-1 flex items-center">
                        <DollarSign size={12} className="mr-1 text-blue-500" />
                        Optimized deployment
                    </div>
                </motion.div>

                {/* Risk Focus Statement */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6 }}
                    className="bg-slate-900 p-5 rounded-xl shadow-lg flex flex-col justify-center relative overflow-hidden"
                >
                    <div className="absolute top-0 right-0 w-16 h-16 bg-rose-500 rounded-full blur-2xl opacity-20 -mr-8 -mt-8" />
                    <div className="relative z-10">
                        <div className="text-xs font-bold text-rose-400 uppercase tracking-wider mb-2 flex items-center">
                            <AlertCircle size={12} className="mr-1" />
                            Flash Risk Alert
                        </div>
                        <p className="text-white text-sm font-medium leading-relaxed">
                            {formatText(brief.risk_focus)}
                        </p>
                    </div>
                </motion.div>
            </div>
        </section>
    );
};

export default ExecutiveBrief;
